package com.mitraecp.api.mitratests.feature.functionalities;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class TableRequest {

    private Integer actionId;
    private ConfigDTO configDTO;
    private Boolean asTextArea;
    private Integer autoIncrementCubeId;
    private String backgroundColor;
    private Integer blockIdUS;
    private Integer border;
    private String borderBottom;
    private String borderLeft;
    private String borderRadius;
    private String borderRight;
    private String borderTop;
    private Boolean canDrill;
    private Boolean canExportXls;
    private Boolean canFocus;
    private Boolean canSwitchComponent;
    private String cardBoardHeaderWidth;
    private String cartesianBlockRef;
    private Boolean chartIsGradient;
    private String chartOrientation;
    private Boolean columnsWithoutScreensSelection;
    private Integer deDimensionId;
    private Integer dimensionId;
    private String dimensionName;
    private Boolean displayLegend;
    private Integer diveId;
    private String documentType;
    private Boolean dynamicImage;
    private Boolean enableCardDragging;
    private Boolean enableDataEntry;
    private Boolean enableHideColumns;
    private Boolean enabledSelectAll;
    private Boolean isChildrenOfFolder;
    private String enableSearch;
    private Boolean enabledStateView;
    private String fileExtension;
    private String font;
    private String fontColor;
    private String fontSize;
    private Boolean funnelPercentage;
    private Integer h;
    private Boolean hasBlocks;
    private Boolean hasBolder;
    private Boolean hasItalic;
    private Boolean hasUnderscore;
    private Integer id;
    private Integer identityId;
    private String imgHeight;
    private String imgWidth;
    private String isAutoIncrement;
    private Boolean isDescriptionAutoIncrement;
    private Boolean isEnable;
    private Boolean isHorizontal;
    private Boolean isInverse;
    private Boolean isPage;
    private LabelDetails labelDetails;
    private Boolean labelHover;
    private String labelHoverColor;
    private Integer labelMenuId;
    private Boolean labelShadow;
    private String labelShadowLevel;
    private String labelTooltip;
    private String labelValue;
    private String legendDirection;
    private String limitedSelectionContent;
    private Boolean lockScreen;
    private String markerFontSize;
    private Integer markerManualScale;
    private Integer markerOrientation;
    private Boolean selectTableText;
    private String maskScreenComponentId;
    private String minFontSize;
    private String numberOfColumns;
    private String originTypeId;
    private String pageText;
    private Integer pbh;
    private Integer pbw;
    private Integer pbx;
    private Integer pby;
    private String position;
    private String principalDynamicImageId;
    private Integer radius;
    private String rangeValue;
    private String refScreenComponentId;
    private Boolean scapePreLoading;
    private Integer screenId;
    private String selectorType;
    private String showActionModal;
    private Boolean showAllAxes;
    private Boolean showLabel;
    private Boolean showLabelUSBased;
    private String sliderIsEnable;
    private Integer sourceId;
    private Boolean suggestContent;
    private String tagShowValue;
    private String tagSize;
    private String text;
    private String textAlign;
    private String title;
    private String tooltip;
    private String transparency;
    private Integer typeId;
    private Boolean undraggable;
    private Boolean useAttributesFromScreen;
    private String visible;
    private Integer w;
    private Integer x;
    private Integer y;
    private Integer z;

}
